spring.application.name=demo

spring.datasource.url=jdbc:mysql://localhost:3306/lightestdungeon
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Logs de Hibernate (errores y warnings)
logging.level.org.hibernate=ERROR

# Para ver SQL que ejecuta Hibernate
logging.level.org.hibernate.SQL=DEBUG

# Para ver los valores de los parámetros (muy útil)
logging.level.org.hibernate.type.descriptor.sql=TRACE

# Opcional: formato bonito del SQL
spring.jpa.properties.hibernate.format_sql=true